using CryEngine;

namespace FairyGUI
{
	/// <summary>
	/// Base class for all kind of fonts. 
	/// </summary>
	public class BaseFont
	{
		/// <summary>
		/// The name of this font object.
		/// </summary>
		public string name { get; protected set; }

		/// <summary>
		///  Can this font be tinted? Will be true for dynamic font and fonts generated by BMFont.
		/// </summary>
		public bool colorEnabled;

		/// <summary>
		/// 
		/// </summary>
		public bool scaleEnabled;

		/// <summary>
		/// The texture of this font object.
		/// </summary>
		public NTexture mainTexture;

		/// <summary>
		/// 
		/// </summary>
		public PackageItem packageItem;

		virtual public void SetFormat(TextFormat format, float fontSizeScale)
		{
		}

		virtual public bool GetGlyphSize(char ch, out float width, out float height)
		{
			width = 0;
			height = 0;
			return false;
		}

		virtual public bool GetGlyph(char ch, GlyphInfo glyph)
		{
			return false;
		}

		public BaseFont()
		{
		}
	}

	/// <summary>
	/// Character info.
	/// </summary>
	public class GlyphInfo
	{
		public Rect vert;
		public Vector2[] uv = new Vector2[4];
		public float width;
		public float height;
		public int channel;
	}
}
